# Generated by Django 4.1.1 on 2022-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_colvo_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='colvo_coin',
            field=models.CharField(max_length=10, verbose_name='Количество монет'),
        ),
    ]
