# Generated by Django 4.1.1 on 2022-10-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_colvo_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='choise_coin',
            field=models.CharField(choices=[('bitcoin', 'BTC'), ('riple', 'XRP')], default='bitcoin', max_length=255),
        ),
    ]
