# Generated by Django 4.1.1 on 2022-10-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_choise_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='choise_coin',
        ),
    ]
