# Generated by Django 4.1.1 on 2022-10-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colvo_coin', models.CharField(max_length=10, verbose_name='Количество монет')),
                ('Email', models.CharField(max_length=50, verbose_name='Почта')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('num_wallet', models.CharField(max_length=30, verbose_name='Номер кошелька:')),
            ],
        ),
    ]
